[project]
name = "f1-data-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dagster>=1.13.3",
    "dagster-dg-cli>=1.13.3",
    "dagster-webserver>=1.13.3",
    "duckdb>=1.5.2",
    "pandas>=3.0.2",
    "pyarrow>=24.0.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "duckdb>=1.0.0",
    "ruff>=0.15.12",
]

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "f1_data_pipeline"

[tool.ruff]
exclude = [
    "**/._*",
]
